FROM python:3.9
ENV RUNNING_INSIDE_DOCKER True
RUN python -m pip install --upgrade pip
WORKDIR /code
RUN pip install poetry
COPY ./pyproject.toml /code/pyproject.toml
COPY ./poetry.lock /code/poetry.lock
COPY ./sri_testing/translator /code/sri_testing/translator
COPY ./tests /code/tests
COPY ./README.md /code/README.md
COPY ./api /code/api
COPY *.env /code
RUN python -m poetry install
EXPOSE 8090
CMD ["uvicorn", "api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8090"]
