# leverage the renci python base image
FROM renciorg/renci-python-image:v0.0.1
RUN python -m pip install --upgrade pip
WORKDIR /code
RUN pip install poetry
COPY pyproject.toml poetry.lock /code/
COPY sri_testing/translator /code/sri_testing/translator
COPY tests /code/tests
COPY README.md /code/README.md
COPY api /code/api
COPY *.env /code
RUN poetry config virtualenvs.create false
RUN poetry install -n --no-ansi
# allow non root user write access to tests dir
RUN chown nru:nru /code/tests
# use non root user
USER nru
# change port to allowed port
EXPOSE 8090
CMD ["poetry", "run", "uvicorn", "api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8090"]


