version: '3.9'

services:

  api:
    build:
      context: .
    ports:
    - "8090:8090"
    # need to tie into code/tests/onehop/results VOLUME
    volumes:
    - results:/code/tests/onehop/results

  dashboard:
    build: "./dashboard"
    ports:
    - "8080:8080"

volumes:
  results:
