version: '3.9'

services:

  api:
    build:
      context: .
    ports:
    - "8090:8090"
    # need to tie into code/tests/onehop/results VOLUME
    environment:
      MONGO_INITDB_HOST: mongo
    env_file:
      - .env
    volumes:
    - results:/code/tests/onehop/results

  dashboard:
    build: ./dashboard
    ports:
    - "80:3000"

volumes:
  results:
