version: '3.9'

services:

  ui:
    build:
      context: .
    ports:
    - "80:80"
    # need to tie into code/tests/onehop/results VOLUME
    volumes:
    - results:/code/tests/onehop/results

  dashboard:
    build: "./dashboard"
    ports:
    - "8080:8080"
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      # TODO: parameterized better Mongodb configuration / secrets
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  results:
